### ISSUE TITLE
Please complete the permission statement

### ISSUE THREAD

**Issue by tarsius** [KMahoney/kpm-list#7]
It appears that you want to license this package under the BSD-2-clause license, but a part of that license is missing. Your text ends with "...the following disclaimer..." but then no disclaimer follows.

Please add the disclaimer. You can use the template from https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29.

You might want to additionally put the license text in a file named `LICENSE` or `COPYING`, then the license is also displayed on Github.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by KMahoney** [comment]
Thanks for pointing that out!

**Comment by tarsius** [comment]
And thanks to you for the fix!
